### ISSUE TITLE
Mokkosuコンパイラがスタックオーバーフローで落ちる場合がある

### ISSUE THREAD

**Issue by enerick** [lambdataro/Mokkosu#11]
メモリが2GB程度のVM環境でプログラムをコンパイルした場合、MokkosuTest内の`Test.mok` 程度のプログラムでも`StackOverflowException`が出てコンパイルが失敗する。

**Comment by lambdataro** [comment]
この問題修正に時間がかかると思いますが、いずれ修正します。

**Comment by lambdataro** [comment]
MokkosuコンパイラがStackOverflowで落ちる問題、修正できました。
