### ISSUE TITLE
ユーザー定義演算子を関数化できない

### ISSUE THREAD

**Issue by kokudori** [lambdataro/Mokkosu#31]
[演算子の関数化](http://lambdataro.sakura.ne.jp/mokkosu/lang/expression/#_14)では特に明記されてないのですが、version 1.1.5でユーザー定義演算子(例えば`$`や`<*>`など)を括弧で囲んでもシンタックスエラーになります。
https://github.com/lambdataro/Mokkosu/blob/cdf02afff242056c731f3a183bef43929716d996/VS2013/MokkosuCore/Parsing/Parser.cs#L1000
これは仕様でしょうか？

**Comment by lambdataro** [comment]
仕様ではなくバグです。次のバージョンで修正します。
